runtime: nodejs20
entrypoint: npm start

network:
  session_affinity: true

handlers:
- url: /js
  static_dir: public/js

- url: /ws
  script: auto

- url: /
  static_files: public/index.html
  upload: public/index.html
  expiration: "0s" # Force no caching for index.html

- url: /.*
  script: auto
