runtime: nodejs22
env: flex

# Add network settings for WebSocket support
network:
  name: default
  # Forward all ports (required for WebSockets)
  forwarded_ports:
    - 8080:8080
    - 80:8080
    - 443:8080

# Add readiness check (critical for WebSockets)
readiness_check:
  path: "/readiness"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/readiness"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Reduce resources to stay within free tier
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
