runtime: nodejs20
entrypoint: npm start

network:
  session_affinity: true

handlers:
- url: /js
  static_dir: public/js

- url: /ws
  script: auto
  instance_websocket_liveness_timeout: 600 # Optional: Increase timeout for WebSockets

- url: /.*
  script: auto
