runtime: nodejs22
env: flex # Use the Flexible Environment for WebSocket support

entrypoint: npm start

network:
  session_affinity: true

handlers:
- url: /.*
  script: auto
  secure: always

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
