steps:
  # Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

  # Build the CSS
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build:css']

  # Deploy to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

timeout: '1600s'
